import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {triviaBankRows,triviaCorrectUsers} from '../dist/admin-trivia.js';
const q={id:'q1',prompt:'Câu hỏi <script>',state:'published',correctAttempts:3,correctUsers:2};
const html=triviaBankRows([q],100);
assert.match(html,/<td>101<\/td>/);assert.match(html,/Lượt đúng/);assert.match(html,/>3<\/td>/);assert.match(html,/2 người · Xem/);assert.match(html,/&lt;script&gt;/);assert.ok(!html.includes('<script>'));
const people=triviaCorrectUsers([{id:'u',name:'Người <script>',email:'a&b@example.invalid',correctAttempts:2,lastCorrectAt:'2026-10-07T00:00:00Z'}]);
assert.match(people,/a&amp;b/);assert.ok(!people.includes('<script>'));
assert.match(triviaCorrectUsers([]),/Chưa có người trả lời đúng/);
const source=await readFile(new URL('../src/admin-trivia.ts',import.meta.url),'utf8');
assert.match(source,/encodeURIComponent\(query\)/);assert.match(source,/correct-users/);assert.match(source,/250/);
assert.ok(!source.includes("querySelector<HTMLElement>('[data-trivia-people]')"),'detail panel selector must never target the opener button');
assert.match(source,/data-trivia-people-panel/);
assert.match(source,/const size=10/);
assert.match(source,/peoplePageSize=100/);
assert.match(source,/correct-users\?offset=\$\{page\}&limit=\$\{peoplePageSize\}/);
assert.match(source,/peopleOffset-peoplePageSize/);
assert.match(source,/peopleOffset\+peoplePageSize<peopleTotal/);
assert.match(source,/data-trivia-bank-state/);
assert.match(source,/class="trivia-bank-filters"/);
assert.match(source,/querySelector\('\.trivia-bank-filters'\)!\.append\(stateFilter\)/);
const css=await readFile(new URL('../admin.css',import.meta.url),'utf8');
assert.match(css,/\.trivia-bank-filters\{display:flex;align-items:flex-end;flex-wrap:wrap/);
assert.match(css,/@media\(max-width:600px\).*trivia-bank-filters/);
assert.match(source,/encodeURIComponent\(state\)/);
assert.match(source,/\[0,1,2\]\.map/);assert(!source.includes('[0,1,2,3,4,5]'));
assert.match(source,/selected\?\.locked\?\{prompt:selected.prompt,choices:selected.choices/);
assert.match(source,/\/publish`.*revision:q.revision/);
assert.match(source,/if\(busy\)return/);
assert.match(source,/<dialog class="trivia-question-dialog" aria-labelledby="trivia-question-title">/);
assert.match(source,/dialog\.showModal\(\)/);
assert.match(source,/schemaAvailable:boolean\|null=null/);
assert.match(source,/schemaAvailable===false\?'Chưa nâng schema Trivia/);
assert.match(source,/schemaAvailable=null;loadError=\(error as Error\)\.message;status\(loadError\)/,'authentication/network errors must not be misreported as a missing schema');
assert.match(source,/dialog\.addEventListener\('cancel',event=>\{if\(saving\)event\.preventDefault\(\)/);
assert.match(source,/catch\(error\)\{editorStatus\(\(error as Error\)\.message\)\}/);
assert(!source.includes('form.hidden'),'form visibility must be managed by the dialog, not inline');
assert.match(css,/\.trivia-question-dialog\{.*max-height:calc\(100dvh - 40px\);overflow:auto/);
assert.match(css,/\.trivia-question-actions\{display:flex;justify-content:flex-end/);
const importer=await readFile(new URL('../src/admin-trivia-import.ts',import.meta.url),'utf8');
assert.match(importer,/querySelector\('\.trivia-bank-filters'\)!\.before\(panel\)/,'import panel must remain outside the editor dialog');
assert.match(triviaBankRows([{...q,state:'draft'}]),/Duyệt công khai/);
const draftRow=triviaBankRows([{...q,state:'draft'}]);
assert.match(draftRow,/<td>Nháp<\/td>/);
assert.match(draftRow,/<div class="actions"><button[^>]*data-trivia-publish[^>]*>Duyệt công khai<\/button><button[^>]*data-trivia-edit/);
assert(!triviaBankRows([q,{...q,state:'retired'}]).includes('data-trivia-publish'));
const layout=await readFile(new URL('../src/admin-layout.ts',import.meta.url),'utf8');assert.match(layout,/\['trivia','Hỏi đáp nhanh'\]/);
console.log('ADMIN_TRIVIA_PASS: numbering, separate attempt/user counts, escaping, search and pagination');
