import assert from 'node:assert/strict';
import {agencyComparison,orderAgencies} from '../dist/agency-comparison.js';
const groups=['transparency','dvc-progress-tree','provide-online-tree','dossier-digitized','handling-satisfaction','formality-online-payment-tree'];
const allowed=['a','b','c','ward'].map(id=>({departmentId:id,departmentName:id==='a'?'Sở Công thương':id,departmentLevel:id==='ward'?'COMMUNE':'PROVINCE'}));
const snapshot=(scores)=>({scope:'all',formalityId:null,datasets:groups.map((group,index)=>({group,children:Object.entries(scores).filter(([id,values])=>values[index]!==undefined).map(([id,values])=>({departmentId:id,apiScore:values[index],apiMaxScore:20}))}))});
const current=snapshot({a:[10,10,10,10,10,10],b:[9,9,9,9,9,9],c:[undefined,0,null,1,2,3],ward:[12,12,12,12,12,12],secret:[20,20,20,20,20,20]});
const previous=snapshot({a:[8,8,8,8,8,8],b:[9,9,9,9,9,9],c:[undefined,0,null,1,2,3],ward:[12,12,12,12,12,12]});
const rows=agencyComparison(current,previous,groups,allowed);
const a=rows.find(row=>row.id==='a');const c=rows.find(row=>row.id==='c');
assert.equal(rows.length,4,'union includes unit absent from first group; forbidden unit excluded');
assert.equal(a.total,60);assert.equal(a.rank,1);assert.equal(a.scoreChange,12);assert.equal(a.rankChange,1);
assert.equal(rows.find(row=>row.id==='b').rankChange,-1);
assert.equal(rows.find(row=>row.id==='ward').rank,1,'different levels never ranked together');
assert.equal(c.total,null);assert.equal(c.rank,null);assert.equal(c.scores['dvc-progress-tree'],0,'zero not missing');
assert.equal(c.scores['provide-online-tree'],undefined,'null not zero');
assert.deepEqual(orderAgencies(rows,'total','cong thuong').map(row=>row.id),['a']);
assert.equal(orderAgencies(rows,'total','').at(-1).id,'c');
assert.deepEqual(orderAgencies(rows,'total','','asc').map(row=>row.id),['b','a','ward','c'],'Ascending totals, missing last');
assert.deepEqual(orderAgencies(rows,'dvc-progress-tree','','asc').map(row=>row.id),['c','b','a','ward'],'Zero before positive scores');
assert.deepEqual(orderAgencies(rows,'total','cong thuong','asc').map(row=>row.id),['a'],'Search preserved in ascending order');
assert.equal(agencyComparison(current,null,groups,allowed)[0].scoreChange,null);
const mismatch={...previous,scope:'formality',formalityId:'different'};
assert(agencyComparison(current,mismatch,groups,allowed).every(row=>row.scoreChange===null));
const differentCohort=snapshot({a:[8,8,8,8,8,8],b:[9,9,9,9,9,9],c:[1,1,1,1,1,1]});
assert.equal(agencyComparison(current,differentCohort,groups,allowed).find(row=>row.id==='a').rankChange,null);
const tied=snapshot({a:[10,10,10,10,10,10],b:[10,10,10,10,10,10],c:[9,9,9,9,9,9]});
assert.deepEqual(agencyComparison(tied,null,groups,allowed).map(row=>row.rank),[1,1,3]);
const missingMaximum=structuredClone(current);missingMaximum.datasets[0].children.find(e=>e.departmentId==='a').apiMaxScore=null;
assert.equal(agencyComparison(missingMaximum,null,groups,allowed).find(row=>row.id==='a').total,null);
const agencyOnly=agencyComparison(current,null,groups,allowed.filter(row=>row.departmentId==='a'));
assert.deepEqual(agencyOnly.map(row=>row.id),['a']);
console.log('AGENCY_COMPARISON_OK: union, six-score total, scope allowlist, same-cohort rank changes, zero/null, search/sort');
