import assert from 'node:assert/strict';
import {renderPaidAnalysis,bindPaidAnalysis,clearPaidAnalysis,stopPaidAnalysisPolling} from '../dist/paid-analysis.js';
const selection={rootDepartmentId:'r',unitId:'u',periodType:'year',year:2026,periodValue:null,scope:'all',capturedAt:'2026-10-06T10:00:00Z'};
let timers=new Map(),next=0,calls=[],buttons={},renders=0;
globalThis.setTimeout=callback=>{timers.set(++next,callback);return next;};
globalThis.clearTimeout=id=>timers.delete(id);
globalThis.document={visibilityState:'visible',querySelector:selector=>selector.includes('aria-labelledby')?null:{focus(){},addEventListener(_,fn){buttons[selector]=fn;}},querySelectorAll:()=>[]};
const job={id:'job',requestToken:'token',state:'queued',queuePosition:2,queueWaitMinutes:10,createdAt:selection.capturedAt,capturedAt:selection.capturedAt,message:'',availableCredits:80,reservedCredits:20,result:null};
globalThis.fetch=async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>url.includes('/latest')?{analysis:job}:url.endsWith('/cancel')?{...job,state:'cancelled',availableCredits:100,reservedCredits:0}:job};};
const bind=()=>bindPaidAnalysis(selection,'csrf',()=>renders++,()=>{},()=>{});
bind();assert.equal(calls.length,0);assert.equal(timers.size,0);
await buttons['[data-analysis-read]']();bind();
assert.match(renderPaidAnalysis(selection,true),/Vị trí 2/);assert.equal(timers.size,1);
const tick=async()=>{const [id,fn]=timers.entries().next().value;timers.delete(id);await fn();};
document.visibilityState='hidden';await tick();assert.equal(calls.length,1);assert.equal(timers.size,1);
document.visibilityState='visible';await tick();assert.equal(calls.length,2);assert(calls[1].url.endsWith('/status'));
bind();stopPaidAnalysisPolling();assert.equal(timers.size,0,'Leaving analysis stops polling');
bind();await buttons['[data-analysis-cancel-job]']();bind();
assert.equal(calls[2].url,'/api/v1/me/analysis/cancel');assert.equal(calls[2].options.headers['X-QD766-CSRF'],'csrf');
assert.equal(timers.size,0,'Terminal state stops polling');assert(calls.every(c=>c.options?.method!=='POST'||c.url.endsWith('/cancel')));
clearPaidAnalysis();assert.equal(timers.size,0);assert(renders>0);
console.log('ANALYSIS_QUEUE_UI_OK');
