import assert from 'node:assert/strict';
import {renderPaidAnalysis,bindPaidAnalysis,clearPaidAnalysis} from '../dist/paid-analysis.js';
const selection={rootDepartmentId:'r',unitId:'u',periodType:'month',year:2026,periodValue:8,scope:'all',capturedAt:'2026-10-07T04:00:00Z',organization:'Xã mẫu',periodLabel:'Tháng 8/2026'};
const ids=['transparency','dvc-progress-tree','provide-online-tree','dossier-digitized','handling-satisfaction','formality-online-payment-tree'];
let handlers=new Map(),calls=[],renders=0;
const inputs=ids.map(id=>({dataset:{analysisSelectGroup:id},checked:true,focus(){},addEventListener(_,handler){this.change=handler;}}));
globalThis.document={querySelector:selector=>selector.includes('aria-labelledby')?null:{focus(){},addEventListener(_,handler){handlers.set(selector,handler);}},querySelectorAll:selector=>selector==='[data-analysis-select-group]'?inputs:[]};
globalThis.fetch=async(url,options)=>{
  if(url.endsWith('/availability'))return {ok:true,json:async()=>({available:true})};
  calls.push({url,options});const body=JSON.parse(options.body);
  return {ok:true,json:async()=>({id:'result',state:'ready',context:{groupIds:body.groupIds},credits:body.expectedCredits,
    message:'',createdAt:selection.capturedAt,capturedAt:selection.capturedAt,result:{cards:[],limitations:[]}})};
};
const bind=()=>bindPaidAnalysis(selection,'csrf',()=>renders++,()=>{},()=>{});
bind();await handlers.get('[data-analysis-start]')();
assert.match(renderPaidAnalysis(selection,true),/<strong>30 Credit<\/strong>/);
handlers.get('[data-analysis-select-none]')();
assert.match(renderPaidAnalysis(selection,true),/data-analysis-confirm disabled/);
await handlers.get('[data-analysis-confirm]')();assert.equal(calls.length,0,'No selected groups cannot submit');
inputs[1].checked=true;inputs[1].change();
assert.match(renderPaidAnalysis(selection,true),/<strong>5 Credit<\/strong>/);
await handlers.get('[data-analysis-confirm]')();await new Promise(resolve=>setImmediate(resolve));
assert.equal(calls.length,1);
const body=JSON.parse(calls[0].options.body);assert.deepEqual(body.groupIds,['dvc-progress-tree']);assert.equal(body.expectedCredits,5);
assert.equal(body.organization,undefined);assert.equal(body.availableGroups,undefined);assert.equal(body.periodLabel,undefined);
clearPaidAnalysis();handlers=new Map();calls=[];
const restricted={...selection,availableGroups:['dossier-digitized']};
bindPaidAnalysis(restricted,'csrf',()=>{},()=>{},()=>{});await handlers.get('[data-analysis-start]')();
const html=renderPaidAnalysis(restricted,true);assert.match(html,/<strong>5 Credit<\/strong>/);
assert.match(html,/data-analysis-select-group="transparency"\s+disabled/);
inputs[0].checked=true;inputs[0].change();
assert.match(renderPaidAnalysis(restricted,true),/<strong>5 Credit<\/strong>/);
assert.equal(calls.length,0);assert(renders>0);
clearPaidAnalysis();let availabilityCalls=0;
globalThis.fetch=async(url)=>{assert(url.endsWith('/availability'),'Disabled feature must not POST');availabilityCalls++;return {ok:true,json:async()=>({available:false})};};
bind();assert.equal(availabilityCalls,0,'No availability request on tab entry');
const first=handlers.get('[data-analysis-start]')();await handlers.get('[data-analysis-start]')();await first;
assert.equal(availabilityCalls,1,'Double click guarded during preflight');
assert.match(renderPaidAnalysis(selection,true),/Tính năng tạm thời không khả dụng do đang trong quá trình nâng cấp\./);
assert.doesNotMatch(renderPaidAnalysis(selection,true),/aria-labelledby="analysis-confirm-title"/);
clearPaidAnalysis();console.log('ANALYSIS_GROUP_SELECTION_OK: 5/group, 30/all, zero guard, availability, selected POST only, no automatic requests');
