import assert from 'node:assert/strict';
import {annualDailyComparison,annualGroupChange} from '../dist/annual-daily-comparison.js';
const day=(reportDate,totalScore)=>({reportDate,totalScore,rank:null,cohortKey:'same',groups:{}});
const history={days:[day('2026-10-08',72),day('2026-10-07',70),day('2026-10-06',71),day('2026-10-05',80)]};
assert.match(annualDailyComparison(history),/\+2,00 điểm/);
assert.match(annualDailyComparison(history,'2026-10-07'),/\+2,00 điểm/);
assert.match(annualDailyComparison(history,'2026-10-06'),/\+1,00 điểm/);
assert.match(annualDailyComparison(history,'2026-10-05'),/Chưa đủ dữ liệu ngày/);
assert.match(annualDailyComparison(history),/type="date"/);
assert.match(annualDailyComparison(history),/annual-calendar-date" aria-hidden="true">07\/10\/2026/);
assert.match(annualDailyComparison(history,'2026-10-07'),/annual-calendar-date" aria-hidden="true">07\/10\/2026/);
assert.match(annualDailyComparison(history),/min="2026-10-06" max="2026-10-07"/);
assert.doesNotMatch(annualDailyComparison(history),/2026-10-05|<select/);
assert.match(annualDailyComparison({days:[day('2026-10-05',80)]}),/disabled/);
assert.match(annualDailyComparison(null),/Chưa có lịch sử ngày/);
assert.doesNotMatch(annualDailyComparison(null),/0,00 điểm/);
assert.match(annualDailyComparison(history),/Dữ liệu mới nhất: 08\/10\/2026/);
assert.match(annualDailyComparison(history),/So với ngày<\/span>/);
assert.match(annualDailyComparison({days:[history.days[0],history.days[2]]}),/Chưa đủ dữ liệu ngày/);
assert.match(annualDailyComparison(null,undefined,false,'Network'),/data-daily-refresh/);
console.log('ANNUAL_DAILY_COMPARISON_OK: latest/selected day, gaps, advisory score, retry');
const groupIds=['transparency','dvc-progress-tree','provide-online-tree','dossier-digitized','handling-satisfaction','formality-online-payment-tree'];
const groups=score=>Object.fromEntries(groupIds.map(id=>[id,{score,maximum:20}]));
const detailed={days:[{...day('2026-10-08',72),groups:groups(12)},{...day('2026-10-07',70),groups:groups(10)},{...day('2026-10-06',71),groups:groups(11)}]};
for(const id of groupIds){
 assert.equal(annualGroupChange(detailed,id),2);
 assert.equal(annualGroupChange(detailed,id,'2026-10-07'),2);
 assert.equal(annualGroupChange(detailed,id,'2026-10-06'),1);
 assert.equal(annualGroupChange(null,id),null);
 assert.equal(annualGroupChange({days:[detailed.days[0],detailed.days[2]]},id),null);
}
assert.equal(annualGroupChange({days:history.days},'transparency'),null);
const missing=structuredClone(detailed);missing.days[1].groups.transparency.score=null;
assert.equal(annualGroupChange(missing,'transparency'),null);
console.log('ANNUAL_GROUP_CHANGE_OK: all six groups share clock dates; no zero/missing-day fabrication');
