import assert from 'node:assert/strict';
import {gauge,gaugeLevel,composition,trendChart} from '../dist/bento.js';
const ids=['transparency','dvc-progress-tree','provide-online-tree','dossier-digitized','handling-satisfaction','formality-online-payment-tree'];
const make=(total=61.89)=>({totalScore:total,groups:ids.map((id,i)=>({id,label:id,maximum:[18,20,12,22,18,10][i],score:{value:10}}))});
assert.match(gauge(61.89,100),/61,89/);
assert.match(gauge(null,100),/Chưa có tổng điểm/);
assert.doesNotMatch(gauge(0,100),/class="gauge-value"/);
for(const [score,label] of [[49.99,'Yếu'],[50,'Trung bình'],[69.99,'Trung bình'],[70,'Khá'],[79.99,'Khá'],[80,'Tốt'],[90,'Tốt'],[90.01,'Xuất sắc']])assert.equal(gaugeLevel(score).label,label);
assert.match(gauge(60,100),/data-gauge-tone="warn"/);
assert.match(gauge(60,100),/stroke-linecap="round" pathLength="100" stroke-dasharray="60 100"/);
assert.match(gauge(60,100),/stop-color="#f97316"/);
assert.doesNotMatch(gauge(60,100),/stop-color="#dc2626"|stop-color="#38bdf8"|stop-color="#16a34a"/);
for(const [score,tone] of [[40,'bad'],[60,'warn'],[75,'fair'],[85,'good'],[95,'excellent']])assert.match(gauge(score,100),new RegExp(`data-gauge-tone="${tone}"`));
assert.match(gauge(60,82),/data-gauge-tone="fair"/);
assert.match(gauge(75,100),/stop-color="#eab308"/);
assert.match(gauge(85,100),/stop-color="#a3e635"/);
assert.match(gauge(95,100),/stop-color="#166534"/);
assert.doesNotMatch(gauge(75,100),/Kém|70–85|&gt;85|background:#38bdf8/);
assert.match(gauge(100,100),/stroke-dasharray="100 100"/);
assert.match(gauge(null,100),/data-gauge-tone="neutral"/);
assert.match(gauge(60,0),/data-gauge-tone="neutral"/);
assert.equal((composition(make()).match(/composition-label/g)||[]).length,6);
const missing=make();missing.groups[0].score.value=null;
assert.match(composition(missing),/Không tính cơ cấu từ dữ liệu thiếu/);
assert.match(trendChart([{label:'Tháng 1/2026',order:1,view:make()}],[]),/Chưa đủ lịch sử/);
const trend=trendChart([{label:'Tháng 1/2026',order:1,view:make(60)},{label:'Tháng 3/2026',order:3,view:make(62)}],ids);
assert.doesNotMatch(trend,/<path d="M[^" ]+ L[^" ]+" fill="none"/); // A missing month must break the line.
assert.match(trendChart([{label:'Tháng 1/2026',order:1,view:make(60)},{label:'Tháng 2/2026',order:2,view:make(62)}],['dvc-progress-tree']),/không phải tỷ lệ hồ sơ/);
assert.equal((trend.match(/data-trend-toggle=/g)||[]).length,6);
assert.equal((trend.match(/data-trend-series=/g)||[]).length,6);
assert.match(trendChart([{label:'Tháng 1/2026',order:1,view:make()},{label:'Tháng 2/2026',order:2,view:make()}],ids,new Set(['transparency'])),/data-trend-series="transparency" hidden/);
console.log('BENTO_OK: authoritative gauge, null vs zero, six-group composition, truthful trend gaps');
