import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {changeTone,rankImprovement} from "../dist/change-tone.js";
for (const value of [1,0.01,10]) assert.equal(changeTone(value),"change-positive");
for (const value of [-1,-0.01,-10]) assert.equal(changeTone(value),"change-negative");
for (const value of [0,-0,null,undefined,NaN,Infinity,0.001,-0.001]) assert.equal(changeTone(value),"change-neutral");
assert.equal(changeTone(rankImprovement(17,16)),"change-positive");
assert.equal(changeTone(rankImprovement(16,17)),"change-negative");
assert.equal(changeTone(rankImprovement(16,16)),"change-neutral");
assert.equal(changeTone(rankImprovement(null,16)),"change-neutral");
const source=readFileSync(new URL("../src/app.ts",import.meta.url),"utf8");
const time=source.slice(source.indexOf("function time():"),source.indexOf("function dimensionValues():"));
assert.match(time,/class="num \$\{changeTone\(delta\)\}"/);
assert.match(time,/changeTone\(rankImprovement\(/);
assert.match(source, /hero-footer"><span class="\$\{changeTone\(rankChange\)\}"/);
assert.match(source, /pillar-meta"><span[^>]*class="\$\{changeTone\(delta\)\}"/);
assert.match(source, /class="num \$\{changeTone\(scoreChange\)\}"/);
assert.match(source, /class="num \$\{changeTone\(rankChange\)\}"/);
const css=readFileSync(new URL("../bento.css",import.meta.url),"utf8");
assert.match(css,/\.change-positive[^}]*color:var\(--green\)/);
assert.match(css,/\.change-negative[^}]*color:var\(--red\)/);
assert.match(css,/\.change-neutral[^}]*color:var\(--muted\)/);
console.log("Comparison colors PASS: score changes, inverse rank direction, zero/missing and all comparison views");
