import assert from 'node:assert/strict';
import ExcelJS from 'exceljs';
import {buildComparisonWorkbook,displayedNumber,readVisibleTable} from '../dist/comparison-export.js';
assert.deepEqual(displayedNumber('1.234,56'),{value:1234.56,format:'#,##0.00'});
assert.deepEqual(displayedNumber('87,3%'),{value:.873,format:'0.0%'});
assert.equal(displayedNumber('17/34'),null);
assert.equal(displayedNumber('—'),null);
const comparison={title:'Bảng xếp hạng',headers:['Hạng','Đơn vị','Điểm','Mức đạt','Chênh lệch'],rows:[['1','Cơ quan có tên rất dài để kiểm tra độ rộng','17,46','87,3%','+1,17'],['2','=1+1','0,00','0%','-2,00']]};
const book=buildComparisonWorkbook(ExcelJS.Workbook,comparison,{organization:'UBND tỉnh',period:'Tháng 10/2026',scope:'Tất cả TTHC',updated:'Điểm: mới · Chi tiết: cũ'});
const restored=new ExcelJS.Workbook();await restored.xlsx.load(await book.xlsx.writeBuffer());
const sheet=restored.worksheets[0];
assert.deepEqual(sheet.getRow(4).values.slice(1),comparison.headers);
assert.equal(sheet.rowCount,6);
assert.equal(sheet.columnCount,5);
assert.equal(sheet.getCell('B6').value,'=1+1');
assert.equal(sheet.getCell('C6').value,0);
assert.equal(sheet.getCell('E5').font.color.argb,'FF059669');
assert.equal(sheet.getCell('E6').font.color.argb,'FFDC2626');
assert.match(sheet.getCell('E5').numFmt,/^\+/);
assert.equal(sheet.getRow(4).height,sheet.getRow(5).height);
assert(sheet.getColumn(2).width>=comparison.rows[0][1].length+3);
assert.equal(sheet.views[0].ySplit,4);
const table={querySelectorAll(selector){return selector==='thead th'?[{textContent:'Hạng'},{textContent:'Điểm'}]:[{hidden:false,cells:[{textContent:'1',colSpan:1},{textContent:'0',colSpan:1}]},{hidden:true,cells:[]}];}};
assert.deepEqual(readVisibleTable(table,'Đang xem'),{title:'Đang xem',headers:['Hạng','Điểm'],rows:[['1','0']]});
console.log('COMPARISON_EXPORT_OK: exact visible columns/rows, numeric formats, frozen header, safe text');
