import assert from 'node:assert/strict';
import ExcelJS from 'exceljs';
import {detailExportEntries} from '../dist/detail-export.js';
import {buildGroupWorkbook} from '../dist/group-export.js';
import {buildAnalysisRows} from '../dist/csv-export.js';
const payment={departmentId:'own',apiScore:7.29,apiMaxScore:10,apiRatio:72.9,metrics:[],parameters:{totalFeeDossierFormality:91,totalFeeFormality:408,totalDossierOnlineFormalityPaymentSuccess:229,totalFeeDossierFormalityDistinct:408,totalDossierOnlinePaymentSuccess:295981,totalDossierFinancialObligation:333245}};
const group={id:'formality-online-payment-tree',label:'Thanh toán trực tuyến',entities:[payment]};
const snapshot={scope:'all',datasets:[]},context={name:'Cơ quan thử',period:'Tháng 10',scope:'Tất cả TTHC',snapshot};
const data={groups:[group],units:[{departmentId:'own',departmentName:'Cơ quan thử',departmentLevel:'COMMUNE'}],accessScope:'agency'};
const before=JSON.stringify(data),book=buildGroupWorkbook(ExcelJS.Workbook,data,context);
const reopened=new ExcelJS.Workbook();await reopened.xlsx.load(await book.xlsx.writeBuffer());
const sheet=reopened.worksheets[0];
assert.equal(sheet.getCell('D7').value,7.29);
assert.deepEqual([sheet.getCell('J7').value,sheet.getCell('P7').value,sheet.getCell('V7').value],[.56,1.4,5.33]);
assert.equal(sheet.getCell('I7').numFmt,'0.00%');
assert.equal(sheet.getCell('H7').numFmt,'#,##0');
assert.equal(sheet.getCell('L7').value,1.44);
assert.doesNotMatch(JSON.stringify(sheet.getSheetValues()),/Hồ sơ có phí, lệ phí không trùng lặp|totalFee/);
assert.equal(JSON.stringify(data),before);
const view={id:'own',name:'Cơ quan thử',groups:[{id:group.id,label:group.label,entity:payment}]};
const rows=buildAnalysisRows(view,snapshot,{label:'Tháng 10'},'Tỉnh thử','Tất cả TTHC','details');
assert.equal(rows.length,4);assert.deepEqual(rows.slice(1).map(r=>r[14]),[.56,1.4,5.33]);
const progress={apiScore:16,apiMaxScore:20,metrics:[],parameters:{totalOnTime:80,totalOverdue:20,totalReceived:100,avgProcessingDays:3.61}};
assert.deepEqual(detailExportEntries('dvc-progress-tree',progress,'all').map(r=>r.key),['totalOnTime','totalOverdue','totalReceived']);
assert.equal(detailExportEntries('dvc-progress-tree',progress,'formality').at(-1).key,'avgProcessingDays');
const metrics=['CITIZEN_DATA_CONNECTED_DOSSIER','CITIZEN_DATA_CONNECTED_FORMALITY'].map(code=>({code,name:'Tên cũ',apiScore:1,apiMaxScore:2}));
const digitized=detailExportEntries('dossier-digitized',{metrics,parameters:{}},'all');
assert.equal(digitized[0].key,'CITIZEN_DATA_CONNECTED_FORMALITY');assert.match(digitized[0].metric.name,/phục vụ giải quyết TTHC/);
const online=detailExportEntries('provide-online-tree',{metrics:[],parameters:{authorityCount:100,fullCount:80,partialCount:10}},'all');
assert(online.some(r=>r.metric.name==='TTHC cung cấp DVCTT toàn trình'));assert(online.every(r=>r.kind==='metric'));
const referenceGroup={id:'provide-online-tree',label:'DVC trực tuyến',entities:[{...payment,apiScore:6,parameters:{}}]};
const referenceBook=buildGroupWorkbook(ExcelJS.Workbook,{...data,groups:[referenceGroup]},{...context,provinceOnlineReference:{unitId:'own',provinceName:'Tỉnh thử',parameters:{authorityCount:100,fullCount:80,partialCount:10}}});
const referenceSheet=referenceBook.worksheets[0];
assert.equal(referenceSheet.getCell('D7').value,6);
assert.equal(referenceSheet.getCell('H7').value,100);
assert.match(referenceSheet.getCell('A4').value,/Chi tiết tham khảo của Tỉnh thử/);
assert.equal(referenceSheet.getCell('J7').value,null);
const noReferenceBook=buildGroupWorkbook(ExcelJS.Workbook,{...data,groups:[referenceGroup]},{...context,provinceOnlineReference:{unitId:'another',provinceName:'Tỉnh thử',parameters:{authorityCount:100,fullCount:80}}});
assert.doesNotMatch(JSON.stringify(noReferenceBook.worksheets[0].getSheetValues()),/TTHC cung cấp DVCTT toàn trình/);
console.log('DETAIL_EXPORT_PARITY_PASS: payment, progress, digitization, online, source preservation, numeric readback');
