import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {renderPeerList} from '../dist/peer-list.js';
import {analyzeProgressScore} from '../dist/progress-scoring.js';
const peers=Array.from({length:34},(_,i)=>({id:String(i),name:`Tỉnh ${i}`,score:90-i}));
const html=renderPeerList(peers,'17');
assert.equal((html.match(/class="peer-row /g)||[]).length,34);
assert.match(html,/tabindex="0"/);
assert.match(html,/class="peer-row mine"><span>Tỉnh 17/);
assert.match(html,/Tỉnh 33/);
assert.match(renderPeerList([{id:'a',name:'<script>',score:1},{id:'b',name:'B',score:1}],''),/&lt;script&gt;/);
assert.equal((renderPeerList([{id:'a',name:'A',score:1},{id:'b',name:'B',score:1}], '').match(/Hạng 1/g)||[]).length,2);
const app=readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');
const body=app.slice(app.indexOf('function progressDetail('),app.indexOf('function metricPoint('));
const n=(value,digits=2)=>value===null?'—':value.toLocaleString('vi-VN',{minimumFractionDigits:digits,maximumFractionDigits:digits});
const render=new Function('analyzeProgressScore','n','int','esc','state',`${body}; return progressDetail;`)(analyzeProgressScore,n,value=>value.toLocaleString('vi-VN'),value=>value,{selectedMetric:null});
const detail=render({apiScore:12.91,apiMaxScore:20,parameters:{totalReceived:33699,totalOnTime:21751,avgProcessingDays:3.96}});
assert.doesNotMatch(detail,/Thời gian giải quyết trung bình|<span>Giải quyết trung bình<\/span>|3,96 ngày/);
const singleProcedure=render({apiScore:12.91,apiMaxScore:20,parameters:{totalReceived:33699,totalOnTime:21751,avgProcessingDays:3.96}},true);
assert.match(singleProcedure,/Thời gian giải quyết trung bình/);
assert.match(singleProcedure,/3,96 ngày/);
assert.match(app,/progressDetail\(entity, state.scope === "formality" && catalogPreview.mode === "single"\)/);
assert.match(detail,/Hồ sơ quá hạn giải quyết/);
assert.doesNotMatch(detail,/Hồ sơ ngoài nhóm|hai chữ số|phần còn lại|progress-formula|<small>hồ sơ/);
assert.match(detail,/<th>Công thức<\/th>/);
assert.match(detail,/Tỷ lệ hồ sơ giải quyết đúng hạn × 20,00/);
assert.doesNotMatch(detail,/Tổng hồ sơ tiếp nhận − Hồ sơ đúng hạn/);
assert.match(detail,/<td>Hồ sơ quá hạn \/ Tổng hồ sơ tiếp nhận × 100%<\/td>/);
assert.match(detail,/12,91 \/ 20,00 điểm/);
assert.match(detail,/11.948 hồ sơ/);
assert(detail.indexOf('<td><button class="row-link">Hồ sơ giải quyết đúng hạn')<detail.indexOf('<td>Hồ sơ quá hạn giải quyết'));
assert(detail.indexOf('<td>Hồ sơ quá hạn giải quyết')<detail.indexOf('<td>Tổng hồ sơ tiếp nhận'));
assert(singleProcedure.indexOf('<td>Tổng hồ sơ tiếp nhận')<singleProcedure.indexOf('<td>Thời gian giải quyết trung bình'));
assert.doesNotMatch(render({apiScore:0,apiMaxScore:20,parameters:{totalReceived:0,totalOnTime:0}}),/NaN|Infinity/);
assert.match(render({apiScore:5,apiMaxScore:20,parameters:{totalReceived:100,totalOnTime:80}}),/Chênh 11,000 điểm/);
const css=readFileSync(new URL('../bento.css',import.meta.url),'utf8');
assert.match(css,/@media\(min-width:901px\).*contain:size/);
assert.match(css,/nearby-list\{[^}]*overflow-y:auto/);
assert.doesNotMatch(app,/rows\.slice\(Math\.max\(0,currentIndex-2\)|comparable\.slice\(Math\.max\(0,position-2\)/);
console.log('GROUP_DETAIL_OK: full peers, ties, escaping, compact progress formulas, bounded scrolling');
