import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const modulePath=process.argv[2]||'web/dist/login-view.js';
const {loginView}=await import(pathToFileURL(resolve(modulePath)).href);
const login=loginView({inviteRequired:true,local:true});
assert.ok(login.includes('Đăng nhập với Google'));
assert.ok(login.includes('/api/v1/auth/google/start'));
assert.ok(login.includes('Bản dùng thử theo lời mời.'));
assert.ok(login.includes('Dữ liệu mô phỏng'));
assert.ok(login.includes('>Đăng nhập</h2>'));
assert.ok(!login.includes('Chào mừng'));
assert.ok(login.includes('Từ dữ liệu đến'));
assert.ok(login.includes('Theo dõi sáu nhóm chỉ tiêu'));
assert.ok(!login.split('<section class="login-form"')[1].includes('được phân quyền'));
assert.ok(!login.includes('type="password"'));
const pending=loginView({pending:true,name:'<script>alert(1)</script>'});
const publicLogin=loginView({inviteRequired:true,publicRegistrationEnabled:true});
assert.ok(publicLogin.includes('Chưa phải thành viên?'));
assert.ok(publicLogin.includes('>Đăng ký ngay!</a>'));
assert.ok(!publicLogin.includes('class="login-google login-register"'));
assert.ok(publicLogin.includes('/api/v1/auth/google/start?register=1'));
assert.ok(!publicLogin.includes('Bản dùng thử theo lời mời.'));
assert.ok(!pending.includes('<script>'));
assert.ok(pending.includes('&lt;script&gt;'));
assert.ok(pending.includes('data-action="logout"'));
assert.ok(!pending.includes('href="/api/v1/auth/google/start"'));
assert.ok(loginView({failed:true}).includes('role="alert"'));
assert.ok(login.includes('@media(max-width:760px)'));
console.log('LOGIN_VIEW_TEST=PASS');
