import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const modulePath=process.argv[2]||'web/dist/login-view.js';
const {loginView}=await import(pathToFileURL(resolve(modulePath)).href);
const login=loginView({inviteRequired:true,local:true});
assert.ok(login.includes('Tiếp tục với Google'));
assert.ok(login.includes('/api/v1/auth/google/start'));
assert.ok(login.includes('Dùng thử theo lời mời'));
assert.ok(login.includes('dữ liệu và credit mô phỏng'));
assert.ok(!login.includes('type="password"'));
const pending=loginView({pending:true,name:'<script>alert(1)</script>'});
assert.ok(!pending.includes('<script>'));
assert.ok(pending.includes('&lt;script&gt;'));
assert.ok(pending.includes('data-action="logout"'));
assert.ok(!pending.includes('href="/api/v1/auth/google/start"'));
assert.ok(loginView({failed:true}).includes('role="alert"'));
assert.ok(login.includes('@media(max-width:760px)'));
console.log('LOGIN_VIEW_TEST=PASS');
