import assert from 'node:assert/strict';
import {renderPaidAnalysis,bindPaidAnalysis} from '../dist/paid-analysis.js';
const selection={rootDepartmentId:'r',unitId:'u',periodType:'year',year:2026,periodValue:null,scope:'all',capturedAt:'2026-10-06T10:00:00Z'};
const buttons={start:{},read:{},confirm:{},cancel:{}};let calls=[];let renders=0;let wallet;
globalThis.window={confirm:()=>{throw new Error('Native browser confirmation must not be used');}};
globalThis.document={querySelector:selector=>(selector.includes('aria-labelledby')||selector.includes('cancel-job'))?null:({focus:()=>{},addEventListener:(_,handler)=>{buttons[selector.includes('start')?'start':selector.includes('confirm')?'confirm':selector.includes('cancel')?'cancel':'read'].click=handler;}}),querySelectorAll:selector=>selector.includes('cancel')?[{addEventListener:(_,handler)=>{buttons.cancel.click=handler;}}]:[]};
let resolveRequest;
globalThis.fetch=(url,options)=>{if(url.endsWith('/availability'))return Promise.resolve({ok:true,json:async()=>({available:true})});calls.push({url,options});return new Promise(resolve=>resolveRequest=resolve);};
assert.match(renderPaidAnalysis(selection,true),/Phân tích - đánh giá/);
assert.match(renderPaidAnalysis(selection,true),/\(Đang thử nghiệm\)/);
assert.match(renderPaidAnalysis(selection,true),/Phân tích điểm số/);
assert.doesNotMatch(renderPaidAnalysis(selection,true),/analysis-group-result/);
assert.doesNotMatch(renderPaidAnalysis(selection,true),/Phân tích bằng Gemini · 20 Credit\/lượt/);
bindPaidAnalysis(selection,'csrf',()=>renders++,()=>{},(available,reserved)=>wallet=[available,reserved]);
assert.equal(calls.length,0,'Mounting/tab entry must not fetch or analyze');
await buttons.start.click();assert.equal(calls.length,0,'Opening dialog must not send a paid request');
assert.match(renderPaidAnalysis(selection,true),/modal collection-confirm/);
assert.match(renderPaidAnalysis(selection,true),/6 nhóm đã chọn/);
assert.match(renderPaidAnalysis(selection,true),/<strong>30 Credit<\/strong>/);
buttons.cancel.click();assert.equal(calls.length,0,'Cancellation must not send a paid request');
assert.doesNotMatch(renderPaidAnalysis(selection,true),/aria-labelledby="analysis-confirm-title"/);
await buttons.start.click();buttons.confirm.click();
assert.equal(calls.length,1);const submitted=JSON.parse(calls[0].options.body);
assert.equal(submitted.expectedCredits,30);assert.equal(submitted.groupIds.length,6);assert(submitted.token);assert.equal(submitted.scope,undefined);assert.equal(submitted.capturedAt,undefined);
assert.equal(calls[0].options.headers['X-QD766-CSRF'],'csrf');
await buttons.start.click();assert.equal(calls.length,1,'Double click must not repeat POST');
resolveRequest({ok:true,status:200,json:async()=>({id:'one',state:'ready',createdAt:'2026-10-06T11:00:00Z',capturedAt:selection.capturedAt,
  availableCredits:80,reservedCredits:0,result:{cards:[{id:'gap',groupId:'dossier-digitized',kind:'priority',title:'<script>',evidence:'Source',action:'Action',recommendation:'Rà soát số hóa.'},{id:'good',groupId:'transparency',kind:'strength',title:'Kết quả tốt',evidence:'Good source',action:'Good action',recommendation:'Duy trì công khai.'},{id:'overview',groupId:'dossier-digitized',kind:'priority',title:'Nhận định mẫu · Số hóa hồ sơ',evidence:'Overview source',action:'Overview action',recommendation:'Kiểm tra điều kiện số hóa.'}],limitations:[]}})});
await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(wallet,[80,0]);assert.match(renderPaidAnalysis(selection,true),/&lt;script&gt;/);
const rendered=renderPaidAnalysis(selection,true);
assert.doesNotMatch(rendered,/Kết quả tốt cần duy trì/);
assert.doesNotMatch(rendered,/Phân tích lại/);
assert.doesNotMatch(rendered,/Nhận định mẫu/);
assert.match(rendered,/Kiểm tra điều kiện số hóa\./);
assert.equal((rendered.match(/data-analysis-result-group=/g)??[]).length,2);
assert.match(rendered,/data-analysis-result-group="transparency"/);
assert.doesNotMatch(rendered,/data-analysis-result-group="dvc-progress-tree"/);
const digitized=rendered.split('data-analysis-result-group="dossier-digitized"')[1];
const [problems,actions]=digitized.split('<h3>Hành động cần thực hiện</h3>');
assert.match(problems,/Source/);assert.doesNotMatch(problems,/Rà soát số hóa\.|Duy trì công khai\.|Good source/);
assert.match(actions,/Rà soát số hóa\./);assert.doesNotMatch(actions,/Duy trì công khai\./);
assert.match(rendered,/Duy trì công khai\./);
assert.doesNotMatch(actions,/>Source<|Good source/);
const read=buttons.read.click();assert.equal(calls.length,2);assert.equal(calls[1].options.method,undefined);
resolveRequest({ok:true,status:200,json:async()=>({analysis:null})});await read;
assert(calls.every(c=>!c.url.includes('googleapis.com')),'API key/provider must stay server-side');
assert(renders>0);
console.log('PAID_ANALYSIS_UI_OK: explicit confirmation, no auto-fetch, double-click guard, saved GET, safe rendering');
