import assert from 'node:assert/strict';
import {paymentIndicators,paymentRows} from '../dist/payment-indicators.js';
import {defaultFormulaConfiguration} from '../dist/formula-reference.js';
const p={totalFeeDossierFormality:91,totalFeeFormality:408,totalDossierOnlineFormalityPaymentSuccess:229,totalFeeDossierFormalityDistinct:408,totalDossierOnlinePaymentSuccess:295981,totalDossierFinancialObligation:333245};
const before=JSON.stringify(p),rows=paymentIndicators(p);
assert.deepEqual(rows.map(x=>x.score),[.56,1.4,5.33]);
assert.equal(Math.round(rows.reduce((s,x)=>s+x.score,0)*100)/100,7.29);
assert.equal(JSON.stringify(p),before);
assert.deepEqual(paymentIndicators({}).map(x=>x.score),[null,null,null]);
assert(paymentIndicators(Object.fromEntries(Object.keys(p).map(k=>[k,0]))).every(x=>x.score===null));
assert.equal(paymentIndicators({...p,totalFeeDossierFormality:408})[0].score,2);
assert.equal(paymentIndicators({...p,totalFeeDossierFormality:Infinity})[0].score,null);
assert.equal(paymentIndicators({...p,totalFeeDossierFormality:409})[0].score,null);
assert.equal(paymentRows(p).length,3);
assert.deepEqual(paymentIndicators({totalFeeDossierFormality:8,totalFeeFormality:40,totalDossierOnlineFormalityPaymentSuccess:18,totalFeeDossierFormalityDistinct:40,totalDossierOnlinePaymentSuccess:2553,totalDossierFinancialObligation:2750}).map(x=>x.score),[.5,1.13,5.57]);
assert.match(paymentRows(p).join(''),/56,13%/);
const group=defaultFormulaConfiguration().groups.find(g=>g.id==='formality-online-payment-tree');
assert.deepEqual(group.items.map(i=>[i.id,i.maximum,i.target]),[['3.5',2,80],['3.5b',2,80],['3.6',6,null]]);
console.log('PAYMENT_INDICATORS_PASS');
