import assert from 'node:assert/strict';
import {registrationBirthDate,registrationFieldError} from '../dist/trial-registration.js';
const today=new Date(2026,9,9);
assert.equal(registrationBirthDate('17/05/1990',today),'1990-05-17');
assert.equal(registrationBirthDate('29/02/2024',today),'2024-02-29');
assert.equal(registrationBirthDate('09/10/2026',today),'2026-10-09');
for(const value of ['29/02/2023','31/04/1990','00/01/1990','01/13/1990','01/01/0000','1990-05-17','1/5/1990','10/10/2026',''])assert.throws(()=>registrationBirthDate(value,today));
console.log('REGISTRATION_BIRTH_DATE_OK');
assert.equal(registrationFieldError('fullName',''),'Vui lòng nhập họ và tên.');
assert.equal(registrationFieldError('fullName','A'),'Họ và tên phải có ít nhất 2 ký tự.');
assert.equal(registrationFieldError('birthDate','05-17-1990'),'Ngày sinh phải có định dạng dd/mm/yyyy.');
assert.equal(registrationFieldError('birthDate','31/02/1990'),'Ngày sinh không hợp lệ.');
assert.equal(registrationFieldError('gender',''),'Vui lòng chọn giới tính.');
assert.equal(registrationFieldError('province',''),'Vui lòng chọn tỉnh/thành phố.');
assert.equal(registrationFieldError('unit',''),'Vui lòng chọn cơ quan, đơn vị.');
assert.equal(registrationFieldError('declarationAccepted',false),'Vui lòng tích xác nhận cam đoan thông tin đăng ký.');
assert.equal(registrationFieldError('workplace',''),'');
assert.equal(registrationFieldError('fullName','Nguyễn Văn A'),'');
console.log('REGISTRATION_VIETNAMESE_VALIDATION_OK');
