import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=name=>readFileSync(new URL('../src/'+name,import.meta.url),'utf8');
const registration=read('trial-registration.ts');
assert.match(registration,/new TomSelect\(province/);
assert.match(registration,/new TomSelect\(unit/);
assert.match(registration,/provinceId:province.value,unitId:unit.value/);
assert.doesNotMatch(registration,/value="national"/);
assert.match(registration,/profile.publicRegistration===true/);
assert.doesNotMatch(registration,/value="province"/);
assert.match(registration,/accessTier:'agency'/);
assert.match(registration,/picker.showPicker\(\)/);
assert.match(registration,/registration\/public/);
assert.match(registration,/email.readOnly=true;email.value=profile.email/);
assert.doesNotMatch(registration,/\[name=fullName\].*value=profile.name/);
assert.match(registration,/\[name=workplace\].*required=false/);
assert.match(registration,/name="declarationAccepted" required/);
assert.doesNotMatch(registration,/value="other"/);
assert.match(registration,/declarationAccepted:.*checked/);
assert.doesNotMatch(registration,/Thông tin cá nhân chỉ dùng để xét duyệt hồ sơ/);
assert.doesNotMatch(registration,/Vui lòng kiểm tra các thông tin được đánh dấu bên trên/);
assert.match(registration,/location.assign\('\/api\/v1\/auth\/google\/start'\)/);
assert.match(registration,/!reply.ok&&reply.status!==303/);
assert.match(registration,/Đăng nhập nếu đã là thành viên/);
assert.doesNotMatch(registration,/Hoàn thiện hồ sơ để quản trị viên xét duyệt/);
assert.match(registration,/X-QD766-CSRF/);
assert.match(registration,/profile.state==='approved'\)return false/);
assert.match(registration,/data-enter hidden/);
assert.match(registration,/if\(!document.hidden\)await check\(\)/);
assert.match(registration,/form.isConnected/);
const admin=read('admin-registration.ts');
assert.match(admin,/sharedRegistrationEnabled/);
assert.match(admin,/ids,decision:button.dataset.review/);
assert.match(admin,/ids.length>100/);
assert.match(admin,/\/\#register=/);
assert.match(admin,/esc\(item.email\)/);
assert.match(admin,/navigator.clipboard.writeText\(url\)/);
const app=read('app.ts');
assert.match(app,/history.replaceState[\s\S]*registration-link/);
assert.match(app,/mountTrialRegistration\(root,localGoogleTrial\)/);
console.log('SHARED_REGISTRATION_UI_OK: searchable agency scope, batch approval, hashed-fragment flow, visibility polling and escaping');
