import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=name=>readFileSync(new URL('../src/'+name,import.meta.url),'utf8');
const registration=read('trial-registration.ts');
assert.match(registration,/new TomSelect\(province/);
assert.match(registration,/new TomSelect\(unit/);
assert.match(registration,/provinceId:province.value,unitId:unit.value/);
assert.doesNotMatch(registration,/accessTier|value="national"|value="province"/);
assert.match(registration,/X-QD766-CSRF/);
assert.match(registration,/profile.state==='approved'\)return false/);
assert.match(registration,/data-enter hidden/);
assert.match(registration,/if\(!document.hidden\)await check\(\)/);
assert.match(registration,/form.isConnected/);
const admin=read('admin-registration.ts');
assert.match(admin,/sharedRegistrationEnabled/);
assert.match(admin,/ids,decision:button.dataset.review/);
assert.match(admin,/ids.length>100/);
assert.match(admin,/\/\#register=/);
assert.match(admin,/esc\(item.email\)/);
assert.match(admin,/navigator.clipboard.writeText\(url\)/);
const app=read('app.ts');
assert.match(app,/history.replaceState[\s\S]*registration-link/);
assert.match(app,/mountTrialRegistration\(root,localGoogleTrial\)/);
console.log('SHARED_REGISTRATION_UI_OK: searchable agency scope, batch approval, hashed-fragment flow, visibility polling and escaping');
