import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
let handlers={},html='',calls=[],clock=0,tick,visibility,round='r1',finished=false,timeout=false,correct=true,failNext=false;
globalThis.performance={now:()=>clock};
globalThis.setInterval=callback=>{tick=callback;return 1};globalThis.clearInterval=()=>{tick=null};
const control=key=>({value:key.split(':')[1],addEventListener:(_event,fn)=>handlers[key]=fn});
const card={set outerHTML(value){html=value;handlers={}},querySelectorAll:()=>[control('choice:0'),control('choice:1')],querySelector:selector=>control(selector)};
globalThis.document={querySelector:()=>card,querySelectorAll:selector=>selector==='[data-trivia-clock]'?[]:[card],addEventListener:(event,fn)=>{if(event==='visibilitychange')visibility=fn},hidden:false};
const question={id:'q1',prompt:'Câu hỏi <script>alert(1)</script>?',choices:['Đúng <b>','Sai'],roundId:'r1',expiresAt:'2026-10-07T00:01:00Z'};
globalThis.fetch=async(url,options)=>{calls.push({url,options});if(failNext){failNext=false;throw new Error('Network failed')}if(url.endsWith('/restart')){round='r2';finished=false;timeout=false;question.roundId=round}
  return {ok:true,json:async()=>url.endsWith('/answer')?{correct,correctIndex:0,explanation:'Đáp án <script>',stats:{score:1,streak:1,best:1,answered:1}}:
    {available:true,question:finished?null:question,roundId:round,serverNow:'2026-10-07T00:00:00Z',timedOut:timeout,stats:{score:0,streak:0,best:1,answered:timeout?1:0}}}};
const {bindTrivia,triviaMarkup}=await import('../dist/trivia.js');
const settle=async()=>{for(let i=0;i<10;i++)await Promise.resolve()};
bindTrivia('csrf');await settle();
assert.equal(calls.length,1);assert.match(html,/HỎI - ĐÁP NHANH/);assert.match(html,/&lt;script&gt;/);assert.ok(!html.includes('<script>'));
assert.match(html,/<div class="trivia-header"><h3>HỎI - ĐÁP NHANH<\/h3><span class="trivia-clock"/);
assert.match(html,/<div class="trivia-body"><div class="trivia-body-content">/);
assert.match(html,/<div class="trivia-actions"><button type="button" data-trivia-submit/);
handlers['choice:0']();await settle();assert.equal(calls.length,1,'choosing is not submission');
bindTrivia('csrf');await settle();assert.equal(calls.length,1,'page rerender does not reload question');
await handlers['[data-trivia-submit]']();await settle();
assert.equal(calls.length,2);assert.equal(calls[1].options.headers['X-QD766-CSRF'],'csrf');assert.deepEqual(JSON.parse(calls[1].options.body),{questionId:'q1',roundId:'r1',choice:0});
assert.match(triviaMarkup(),/Đúng! \+1 điểm/);assert.match(html,/Điểm <b>1/);assert.match(html,/Câu tiếp theo/);assert.ok(!html.includes('<script>'));
handlers['[data-trivia-next]']();await settle();assert.equal(calls.length,3);
clock=59000;tick();await settle();assert.equal(calls.length,3,'countdown does not fetch every second');
timeout=true;clock=61000;tick();await settle();assert.equal(calls.length,4);assert.match(html,/Hết 60 giây/);
finished=true;handlers['[data-trivia-next]']();await settle();assert.match(html,/Trả lời lại từ đầu/);assert.ok(!html.includes('Kiểm tra câu hỏi mới'));
handlers['[data-trivia-restart]']();await settle();assert.equal(calls.at(-1).url,'/api/v1/me/trivia/restart');assert.deepEqual(JSON.parse(calls.at(-1).options.body),{roundId:'r1'});assert.match(html,/Gửi đáp án/);
handlers['choice:0']();await handlers['[data-trivia-submit]']();await settle();
assert.match(html,/Tiếp sau 15 giây/);const afterAnswer=calls.length;
clock+=14000;tick();await settle();assert.equal(calls.length,afterAnswer,'wait the full 15 seconds');
bindTrivia('csrf');clock+=1000;tick();tick();await settle();assert.equal(calls.length,afterAnswer+1,'one GET, no duplicate or re-scoring');assert.equal(calls.at(-1).options.method,undefined);assert.match(html,/Gửi đáp án/);
correct=false;handlers['choice:1']();await handlers['[data-trivia-submit]']();await settle();assert.match(html,/Chưa đúng\. Đáp án &lt;script&gt;/);assert(!html.includes('Chuỗi đúng đã về 0'));
const afterWrong=calls.length;globalThis.document.hidden=true;clock+=16000;tick();await settle();assert.equal(calls.length,afterWrong,'no background assignment while tab hidden');
globalThis.document.hidden=false;visibility();await settle();assert.equal(calls.length,afterWrong+1,'resume advances overdue result');
handlers['choice:0']();await handlers['[data-trivia-submit]']();await settle();clock+=15000;failNext=true;tick();await settle();const failedCalls=calls.length;
assert.match(html,/Network failed/);assert.match(html,/Câu tiếp theo/);clock+=1000;tick();await settle();assert.equal(calls.length,failedCalls,'network failure uses retry backoff');
clock+=9000;tick();await settle();assert.equal(calls.length,failedCalls+1);assert.match(html,/Gửi đáp án/);
handlers['choice:0']();await handlers['[data-trivia-submit]']();await settle();finished=true;clock+=15000;tick();await settle();assert.match(html,/Trả lời lại từ đầu/);assert.equal(tick,null,'stop timer when bank exhausted');
const css=await readFile(new URL('../bento.css',import.meta.url),'utf8');
assert.match(css,/\.sidebar \.account-zone:has\(\.trivia-card\)\{[^}]*flex:1[^}]*margin-top:18px/);
assert.match(css,/\.trivia-body\{[^}]*min-height:0[^}]*overflow-y:auto/);
assert.match(css,/\.trivia-body-content\{[^}]*margin-block:auto/);
assert.match(css,/\.trivia-card \.trivia-header,\.trivia-card \.trivia-stats,\.trivia-card \.trivia-actions\{flex-shrink:0\}/);
console.log('TRIVIA_UI_PASS: explicit submit, 60s deadline, 15s result advance, manual/hidden/retry/exhausted guards, replay, no per-second fetch');
