/** Shared presentation labels for both dashboard and Excel exports. */
export const parameterLabels: Record<string,string> = {
  averageScore:"Điểm đánh giá trung bình", avgProcessingDays:"Số ngày xử lý trung bình",
  classifiedPetitions:"Số phản ánh, kiến nghị đã phân loại",
  totalDossierFinancialObligation:"Hồ sơ có nghĩa vụ tài chính",
  totalDossierOnlineFormalityPaymentSuccess:"Hồ sơ thanh toán trực tuyến thành công theo thủ tục",
  totalDossierOnlinePaymentSuccess:"Hồ sơ thanh toán trực tuyến thành công",
  totalDossiers:"Tổng số hồ sơ", totalFeeDossierFormality:"Hồ sơ có phát sinh phí, lệ phí",
  totalFeeDossierFormalityDistinct:"Hồ sơ có phí, lệ phí không trùng lặp",
  totalFeeFormality:"Thủ tục có phát sinh phí, lệ phí", totalOnTime:"Hồ sơ giải quyết đúng hạn",
  totalOverdue:"Hồ sơ quá hạn", totalPetitions:"Tổng số phản ánh, kiến nghị", totalReceived:"Tổng hồ sơ tiếp nhận",
  totalCompleted:"Hồ sơ đã giải quyết",
  fullCount:"TTHC cung cấp dịch vụ công trực tuyến toàn trình",
  partialCount:"TTHC cung cấp dịch vụ công trực tuyến một phần",
  authorityCount:"TTHC thuộc phạm vi quản lý",
  channelTotalSum:"Tổng số hồ sơ theo hình thức nộp",
  onlineOnTimeSum:"Hồ sơ trực tuyến xử lý đúng hạn",
  channelDirectSum:"Hồ sơ nộp trực tiếp", channelOnlineSum:"Hồ sơ nộp trực tuyến",
  channelPostalSum:"Hồ sơ nộp qua bưu chính", onlineOverdueSum:"Hồ sơ trực tuyến xử lý quá hạn",
  onlineDossierCount:"Dịch vụ công trực tuyến có phát sinh hồ sơ",
  onlineServiceTotal:"Tổng số dịch vụ công trực tuyến",
};
