type TrialAccount={id:string;name:string;email:string|null;active:boolean;admitted:boolean;canCollect:boolean;credits:number;reservedCredits:number};
type Ledger={availableCredits:number;reservedCredits:number;items:{type:string;amount:number;availableAfter:number;reservedAfter:number;at:string;details:Record<string,unknown>}[]};
type Api=<T>(path:string,body?:unknown)=>Promise<T>;
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));

export async function installTrialCreditManager(root:HTMLElement,api:Api):Promise<void>{
  const policy=await api<{trialCreditManagement?:boolean;localSimulation?:boolean}>("access-policy");
  if(!policy.trialCreditManagement)return;
  const section=document.createElement("section");
  section.innerHTML=`<h2>Quyền khai thác & credit thử nghiệm</h2><p>Quyền xem tỉnh/cơ quan không tự cấp quyền khai thác TTHC. Credit cấp thêm được ghi vào sổ giao dịch; chưa có thanh toán.</p>${policy.localSimulation?'<p><strong>Mô phỏng local — không đổi tài khoản hoặc credit production.</strong> <a href="/local-trial.html">Bàn thử nghiệm</a></p>':""}<form id="credit-form"><div class="form-grid"><label>Tài khoản<select id="credit-account" required></select></label><label>Quyền khai thác<select id="credit-permission"><option value="true">Cho phép yêu cầu TTHC</option><option value="false">Không cho phép yêu cầu mới</option></select></label><label>Cấp thêm credit<input id="credit-amount" type="number" min="0" max="100000" value="0" required></label><label>Lý do<input id="credit-reason" value="Cấp credit thử nghiệm" minlength="3" maxlength="240" required></label></div><div class="actions"><button class="primary" id="credit-save">Lưu quyền / cấp credit</button></div></form><p id="credit-message" role="status"></p><p id="credit-balance"></p><div class="scroll"><table><thead><tr><th>Giao dịch</th><th>Credit</th><th>Khả dụng sau</th><th>Đang giữ sau</th><th>Thời điểm</th></tr></thead><tbody id="credit-ledger"></tbody></table></div>`;
  root.append(section);
  const get=<T extends HTMLElement>(id:string)=>section.querySelector<T>(`#${id}`)!;
  let accounts:TrialAccount[]=[],operationId=crypto.randomUUID(),inFlight=false;
  const labels:Record<string,string>={topup:"Cấp credit",reserve:"Giữ credit",charge:"Trừ khi thành công",release:"Hoàn credit",adjustment:"Điều chỉnh"};
  async function ledger(){const id=get<HTMLSelectElement>("credit-account").value;if(!id)return;const body=await api<Ledger>(`admin/accounts/${id}/credits`);get("credit-balance").textContent=`Khả dụng: ${body.availableCredits.toLocaleString("vi-VN")} · Đang giữ: ${body.reservedCredits.toLocaleString("vi-VN")}`;get("credit-ledger").innerHTML=body.items.map(r=>`<tr><td>${esc(labels[r.type]??r.type)}</td><td>${r.amount.toLocaleString("vi-VN")}</td><td>${r.availableAfter.toLocaleString("vi-VN")}</td><td>${r.reservedAfter.toLocaleString("vi-VN")}</td><td>${new Date(r.at).toLocaleString("vi-VN")}</td></tr>`).join("")||'<tr><td colspan="5">Chưa có giao dịch.</td></tr>';}
  async function selectAccount(){const a=accounts.find(a=>a.id===get<HTMLSelectElement>("credit-account").value);get<HTMLSelectElement>("credit-permission").value=String(a?.canCollect??false);operationId=crypto.randomUUID();await ledger();}
  async function refreshAccounts(){const selected=get<HTMLSelectElement>("credit-account").value;accounts=(await api<TrialAccount[]>("admin/accounts")).filter(a=>a.active&&a.admitted);get("credit-account").innerHTML=accounts.map(a=>`<option value="${a.id}">${esc(a.name)}${a.email?" · "+esc(a.email):""}</option>`).join("");if(accounts.some(a=>a.id===selected))get<HTMLSelectElement>("credit-account").value=selected;await selectAccount();}
  function error(e:unknown){get("credit-message").textContent=e instanceof Error?e.message:String(e);}
  get("credit-account").addEventListener("change",()=>{void selectAccount().catch(error);});
  for(const id of ["credit-permission","credit-amount","credit-reason"])get(id).addEventListener("input",()=>{operationId=crypto.randomUUID();});
  get("credit-form").addEventListener("submit",event=>{event.preventDefault();if(inFlight)return;inFlight=true;const button=get<HTMLButtonElement>("credit-save");button.disabled=true;void (async()=>{try{await api(`admin/accounts/${get<HTMLSelectElement>("credit-account").value}/trial-credit`,{operationId,canCollect:get<HTMLSelectElement>("credit-permission").value==="true",amount:Number(get<HTMLInputElement>("credit-amount").value),reason:get<HTMLInputElement>("credit-reason").value});get("credit-message").textContent="Đã lưu. Người dùng tải lại trang để nhận giao diện quyền mới.";get<HTMLInputElement>("credit-amount").value="0";await refreshAccounts();}catch(e){error(e);}finally{inFlight=false;button.disabled=false;}})();});
  await refreshAccounts();
}
